version: 1.0
os: linux
files:
  - source: target/basicspringbootwebapplication-0.0.1-SNAPSHOT.jar
    destination: /basicspringbootwebapplication/basicspringbootwebapplication-0.0.1-SNAPSHOT.jar
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
