version: 0.2

phases:
  build:
    commands:
       - cd basicspringbootwebapplication && mvn package
artifacts:
  files:
    - basicspringbootwebapplication/target/basicspringbootwebapplication-0.0.1-SNAPSHOT.jar
    - basicspringbootwebapplication/cicd/aws/ec2/scripts/start_server.sh
    - basicspringbootwebapplication/cicd/aws/ec2/scripts/stop_server.sh
    - basicspringbootwebapplication/cicd/aws/ec2/appspec.yml
