version: 0.2

phases:
  build:
    commands:
       - cd basicspringbootwebapplication/basicspringbootwebapplication && mvn test && mvn package
artifacts:
  files:
    - basicspringbootwebapplication/basicspringbootwebapplication/target/basicspringbootwebapplication-0.0.1-SNAPSHOT.jar
