version: 0.2

phases:
  build:
    commands:
       - cd basicspringbootwebapplication && mvn package
artifacts:
  base-directory: 'basicspringbootwebapplication,basicspringbootwebapplication/cicd/aws/ec2'
  files:
    - target/basicspringbootwebapplication-0.0.1-SNAPSHOT.jar
    - appspec.yml
